### ISSUE TITLE
Publish workflowr projects to RStudio Connect

### ISSUE THREAD

**Issue by antass** [jdblischak/workflowr#273]
First of all, thank you so much, John, for this awesome package. I've been using workflowr for several years and I'm even starting to have some success in convincing others to use it haha :) I cannot imagine starting a new project without workflowr!

That said, I would love to be able to push a workflowr website to RStudio Connect. 

Judging from the errors I get trying to deploy a site (see below), it seems to be a matter of how Connect compiles the .Rmd's. It basically wants to simply grab a single .Rmd file, knit it and publish. It is not aware of the folder structure of a workflowr project (it doesn't understand that data and extra code live in a folder sibling to the analysis folder for example, nor does it know what to do with the `_site.yml` file or the table of contents).

Below is the truncated log (note the "permission denied" error; this folder is writable if publishing Shiny apps or single-page .Rmd's; just not when pushing workflowr websites).

```[Connect] 2022/07/05 20:14:36.383312709 Installing readxl (1.4.0) ... 
[Connect] 2022/07/05 20:14:36.393818771 Using cached readxl.
[Connect] 2022/07/05 20:14:36.393932181 	OK (symlinked cache)
[Connect] Completed packrat build against R version: '4.1.2'
[Connect] Launching R Markdown document...
[Connect] 2022/07/05 20:14:36.633551338 Running on host: rstudio-connect
[Connect] 2022/07/05 20:14:36.640154843 Linux distribution: Ubuntu 20.04.3 LTS (focal) 
[Connect] 2022/07/05 20:14:36.641571127 Using Packrat dir /opt/rstudio-connect/mnt/app/packrat/lib/x86_64-pc-linux-gnu/4.1.2
[Connect] 2022/07/05 20:14:36.644244063 LANG: C.UTF-8
[Connect] 2022/07/05 20:14:36.644257696 R version: 4.1.2
[Connect] 2022/07/05 20:14:36.644277964 rmarkdown version: 2.14
[Connect] 2022/07/05 20:14:36.644283597 knitr version: 1.39
[Connect] 2022/07/05 20:14:36.644361232 reticulate version: (none)
[Connect] 2022/07/05 20:14:36.644509933 Using pandoc: /opt/rstudio-connect/ext/pandoc/2.16
[Connect] 2022/07/05 20:14:37.176643417 Error: [EACCES] Failed to make directory '/opt/rstudio-connect/mnt/app/../public': permission denied
[Connect] 2022/07/05 20:14:37.176855104 Execution halted
[Connect] Unable to render the deployed content: Rendering exited abnormally: exit status 1
[Connect] Failure emailing the error: Unable to construct URLs for email: Server.Address is not defined in configuration file.
GET /__api__/applications/80/config 11ms
----- Deployment log finished at  2022-07-05 20:14:37  -----
```

I'd be happy to provide more logs and help troubleshoot and brainstorm, if you feel this feature would be worthwhile! Thanks again!

**Comment by jdblischak** [comment]
> First of all, thank you so much, John, for this awesome package. I've been using workflowr for several years and I'm even starting to have some success in convincing others to use it haha :) I cannot imagine starting a new project without workflowr!

@antass Thanks for the wonderful feedback! It means a lot.

> I would love to be able to push a workflowr website to RStudio Connect.

I would also love this. What command did you use? Did you try [`rsconnect::deploySite()`](https://rstudio.github.io/rsconnect/reference/deploySite.html)? I think something like the code below should work, though you may need to specify the argument `account` for authentication.

```R
library("rsconnect")
deploySite()
```

Please give it a try and copy-paste the output. Thanks!

**Comment by antass** [comment]
Wow, thanks so much for the suggestion. For some reason, I didn't occur to me that Connect would have a specialized function to specifically deploy sites. With very minimal wrangling, it worked!!!

1. I did not have to specify any authentication/account information, as I only use one account and `rsconnect` by default uses that.
2. I had to modify the `siteDir` parameter. It defaults to `getwd()`, which is supposed to contain `index.Rmd` with the `site:` parameter. However, in `workflowr` projects that file lives in the `analysis/` directory.
3. Also, when specifying the directory, I used `here` to expand the path (just simply providing the name of a subdirectory under wd did not work). 
4. Finally (and this is strictly cosmetic), the `reconnect::deploySite()` function requires the name of the site/app and `Application name must be between 3 and 64 alphanumeric characters, dashes, and underscores.` This is weird, because periods are allowed when using the RStudio Publish button.

These didn't work at all / didn't work as expected:

```
rsconnect::deploySite()
rsconnect::deploySite(siteDir = "analysis")
rsconnect::deploySite(siteDir = here("analysis"))
rsconnect::deploySite(siteDir = here("analysis"), siteName = "AG-120-881-BC-001-glioma.analysis.20200226")
```

This worked:
```
rsconnect::deploySite(siteDir = here("analysis"), siteName = "AG-120-881-BC-001-glioma_analysis_20200226")
```

A `workflowr` site with 20 subpages is now deployed :) thank you!

**Comment by jdblischak** [comment]
Wonderful! I'm glad that function worked.

If you're interested in contributing and have available bandwidth, an entry on deploying workflowr with RStudio Connect would be perfect for the vignette on alternative deployment strategies. I can answer any questions you might have about contributing via Git/GitHub

https://workflowr.github.io/workflowr/articles/wflow-08-deploy.html
https://github.com/workflowr/workflowr/blob/main/vignettes/wflow-08-deploy.Rmd
